name: Sync to Hugging Face Space
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.WK_TOKEN }}
        run: git push --force https://islammen:$HF_TOKEN@huggingface.co/spaces/islammen/handly_testing HEAD:main
